### ISSUE TITLE
strange readings 

### ISSUE THREAD

**Issue by Gior80** [CalPlug/ADE7953-Wattmeter#3]
Hello! 
I'm using your library to connect an ade7953 to an eps32.  

I got this strange reading and I cannot figure out if I'm facing a communication problem 

I'm using pin 13 for CS on the chip. FFFFFFFF is  -1  on AP_NOLOAD registry. this indicate some problems ?   I can't figure out reading datasheet as this value should be 1 or 0

APNOLOAD (hex): FFFFFFFF
Vrms (V): -1.00
IrmsA (mA): -0.00
Apparent Power A (mW): 0.67
Active Power A (mW): 0.67
Rective Power A (mW): -0.67
Power Factor A (x100): 0.00
Active Energy A (hex): -1

**Comment by mjklopfer** [comment]
Arduino pin 13 is typically the clock for the Arduino Uno board for SPI  (https://www.arduino.cc/en/Reference/SPI and https://playground.arduino.cc/Code/Spi).  Check pins to make sure things are OK as you are using them.  

You can also try to o-scope it or use a logic analyzer (we use a Saleae-8) and make sure you are getting returns. Check out our test out documents for sample readouts from known functioning boards.

There is an SPI version for the Arduino Uno/ESP8266 and then a different version for the ESP32, as well as an Arduino Uno, tested I2C version posted.  All are tested as functional in most current posted version.

Please be sure to review the checkout guide: https://github.com/CalPlug/ADE7953-Wattmeter/blob/master/Documents/Construction%20of%20Wattmeter.pdf

**Comment by Gior80** [comment]
Thanks, 

I read the guide and it give me nice information.  looking at picture number 9.  looks I have a faulty wattmeter.

just some question cause u probably have this problem before me: 

1) how u determine the IC is faulty? 
2) how, during assembly u damage the component ? 
3) with ic off is there a certain way to verify component is ok? (ex. ground check on +/- pin) 

Thanks!

**Comment by Gior80** [comment]
think I found the problem.   I'm using GPIO14 ( sorry for the error ) as CS pin. 

I see in example there's local_SS variable defined a 14,  so same as mine for test.   

what is happening:   if,  after the loading and Ade  initialisation ,   you print out SCK,MOSI,MISO,CS ( doing it in loop) 

void loop() {
  Serial.println(MOSI);
  Serial.println(MISO);
  Serial.println(SCK);
  Serial.println(SS);
  
what I got in answer is : 

23
19
18
5  <<<<<<<<<<<<it shouldn't be 14???
 
APNOLOAD (hex): FFFFFFFF
Vrms (V): -0.00
IrmsA (mA): -0.00
Apparent Power A (mW): 0.67
Active Power A (mW): 0.67
Rective Power A (mW): -0.67
Power Factor A (x100): 0.00
Active Energy A (hex): -1

**Comment by mjklopfer** [comment]
The SS pin on SPI is just a GPIO that triggers the IC to become active on LOW (for the ADE7953),  Whatever it is defined as, use, or redefine to whatever pin you are using.  It is not part of the Arduino Uno's "Hardware SPI" pins.

You really need to use an oscilloscope or (preferably) a logic analyzer to see what is going on for troubleshooting.  Otherwise you are basically shooting in the dark and using an advanced guess and check method.

Applying the Anna Karenina principle to this, there are many things that can cause the fault you are seeing.  it can be mis-assigned pins, bad components, component mis-population, etc.  Literally anything in your design can cause non-functionality.  We just supply a design and a library.  How you build out your design is highly variable.   We do know the fundamental design is functional along with the posted libraries. 

 This project is provided to the community free of charge without support.  We expect anyone using it to know basic electronics and firmware troubleshooting procedures.  The intent of this project is to expedite others in developing solutions similar to the one we presented.

**Comment by Gior80** [comment]
I just buy an oscilloscope cause you are right in this sense.  no way to test spi communication without and no way to understand the problem with no sure measurements   
gonna make tests and then see results. 
About reset_iso pin instead ,  could you explain me more about hoe it work?  it is always "high" except for resetting the Ade at beginning ?

**Comment by Gior80** [comment]
can be closed .  that was an absolutely stupid wiring error 👍 . damn!!!!
thanks for your time :)

**Comment by mjklopfer** [comment]
Beyond the SPI pins on the boards (assuming the SPI version) there is an optically isolated RESET pin and an optically isolated Interrupt request (IRQ).  In the V4 board there is also a SELECT input.

The RESET is an input.  We inverted the reset pin so the board's user wouldn't need to pull it high to make the ADE7953 operate.  Unless you plan to reset the ADE7953 in operation, you can leave unconnected.

The IRQ pin is an isolated output.  Unless you are using the using the IRQ features of the ADE7953 (say to trigger a flag above a specific accumulated load or timed waveform sampling), you can leave that pin unconnected.

The SELECT input allows you to sample from one of two possible voltage channel inputs sequentially.  This can be used with single-phase inputs for ground fault detection, unpolarized plugs (ambiguous input for line vs. neutral), or measurement of split-phase (2 phase) AC sources such as 240VAC supplies. 

Good luck with your project!

**Comment by jeykayaem** [comment]
hi,getting the same error
